config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users
  resources :articles do
    resources :comments
  end
  
  root :to => 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here.
    # See the CanCanCan's wiki for syntax details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    
    user ||= User.new # guest user (not logged in)
    
    # admin user can operate anything
    if user.can_admin?
      can :manage, :all
    else
      can :manage, Article, :user_id => user.id
      # anyone should be able to read published articles
      can :read, Article, :published => true
      # anyone should be able to create new articles
      can :create, Article
      
      # anyone should be able to read comments of & comment on published articles
      can [:read, :create], Comment, :article => { :published => true }
      # the article's authors should be able to delete comments as they wish
      # also they can read comments on their own article even in unpublished state
      can [:read, :destroy], Comment, :article => { :user_id => user.id }
      # the commenter should be able to delete own comments as long as the article is published
      can :destroy, Comment, { :user_id => user.id, :article => { :published => true } }
      
      # also note that no one can't modify the existing comments (except admin)
    end
    
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true
    
    before_save :do_publish
    
    scope :published, -> { where(published: true) }
    scope :unpublished, -> { where(published: false) }
    
    # class method for handling search queries
    def self.search(search)
      where("title ILIKE ? OR text ILIKE ?", "%#{search}%", "%#{search}%") 
    end
    
    def do_publish
      if self.published == true
        self.published_at = Time.now
      else
        self.published_at = nil
      end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
USER_ROLES = ['user', 'admin']

class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :role, :inclusion => USER_ROLES
  
  def can_admin?
    if role == "admin"
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
  private
  
  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.info "CanCan denied access"
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  load_and_authorize_resource
  
  def index
    @searched = false
    if params[:search]
      @searched = true
      @articles = Article.search(params[:search])
    else
      @articles = Article.all
    end
    
    unless current_user.can_admin?
      @articles = @articles.where("published = true OR user_id = ?", current_user.id)
    end
    
    @articles = @articles.order(published_at: :desc).includes(:user)
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def create
    #render plain: params[:article].inspect
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path
    else
      redirect_to new_article_path, :flash => { :error => @article.errors.full_messages.join(', ') }
    end
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params) # invokes validation
      redirect_to @article
    else
      redirect_to edit_article_path, :flash => { :error => @article.errors.full_messages.join(', ') }
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to articles_path
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :text, :published)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource :article
  load_and_authorize_resource :comment, :through => :article
  
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article), :flash => { :error => @comment.errors.full_messages.join(', ') }
    end
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def new
  end
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_html_string(user)
    if user.nil?
      "You are not logged in"
    else
      super_string = ""
      if user.can_admin?
        super_string = "<span class=\"navbar-text\" style='color: red'>Superuser</span>"
      end
      "<span class=\"navbar-text\"> #{user.name} (#{user.email}) &mdash; </span>" + super_string
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
  <p>
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Your Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% if @searched %>
  <h3>Found <%= @articles.count %> articles</h3>
<% else %>
  <h3>Total articles: <%= @articles.count %></h3>
  <h3>Published today: <%= @articles.where("published_at >= ?", Time.zone.now.beginning_of_day).count %></h3>
<% end %>

<%= form_tag(articles_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
  <%= submit_tag "Search" %>
<% end %>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Published</th>
      <th>Comments</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.user.name %></td>
      <td><%= article.published_at && article.published_at.to_formatted_s(:long) %></td>
      <td><%= article.comments.count %></td>
      <td><%= link_to 'Read', article_path(article) %></td>
      <td>
        <% if can? :update, article %>
          <%= link_to 'Edit', edit_article_path(article) %>
        <% end %>
      </td>
      <td>
        <% if can? :destroy, article %>
          <%= link_to 'Delete', article_path(article),
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Create a new article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>
<p>
  <strong>Author:</strong>
  <%= @article.user.name %>
</p>
<p>
  <%= @article.text %>
</p>

<h3><%= pluralize(@article.comments.count, "comment") %></h3>
<%= render @article.comments %>
 
<h3>Add a comment:</h3>
<%= render 'comments/form' %>

<% if can? :update, @article %>
  <%= link_to 'Edit', edit_article_path(@article) %>
<% end %>

app/views/comments/_comment.html.erb
<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <td><strong><%= comment.user.name %></strong>: </td>
  <td><%= comment.body %> </td>
  <td>
    <% if can? :destroy, comment %>
      | <%= link_to 'Delete', [comment.article, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
    <% end %>
  </td>
</table>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Social Network</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-toggleable-sm navbar-fixed-top navbar-inverse bg-inverse main-nav">
      <div class="container">
          <ul class="nav navbar-nav">
              <li class="nav-item active">
                  <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
          </ul>
          <ul class="nav navbar-nav mx-auto">
              <li class="nav-item">
                <%= link_to 'Simple Socialnet', root_path, class: 'nav-link' %>
              </li>
          </ul>
          <%= user_html_string(current_user).html_safe %>
          <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'nav-link') %>
                </li>
              <% end %>
          </ul>
      </div>
  </nav>
  <div class="container">
    <%= render 'layouts/messages' %>
    <div class="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true%>
  </p>
 
  <p>
    <%= f.label :kana %><br>
    <%= f.text_field :kana %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>